name: User Story
description: Crear una nueva Historia de Usuario
title: "[HU] "
labels:
  - user story
body:
  - type: textarea
    id: description
    attributes:
      label: Descripción
      description: Describe la necesidad desde la perspectiva del usuario.
      value: |
        Como [tipo de usuario], quiero [acción o necesidad], para [beneficio].
      placeholder: "Ejemplo: Como estudiante, quiero consultar mis exámenes disponibles, para saber cuáles puedo rendir."
    validations:
      required: true

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Criterios de aceptación
      description: Define las condiciones que deben cumplirse para considerar aceptada la Historia de Usuario.
      value: |
        - Dado que [condición inicial],
        - Cuando [acción realizada],
        - Entonces [resultado esperado].
      placeholder: "Agrega los criterios necesarios."
    validations:
      required: true

  - type: textarea
    id: dependencies
    attributes:
      label: Dependencias
      description: Indica otras Issues de las que depende esta Historia de Usuario. Déjalo vacío si no existen.
      placeholder: "Ejemplo: Depende de #123"
    validations:
      required: false